# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181026_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
